@host=https://httpbin.org

{{+
  const token = "encryptedtokenvalue";
  const correlationId = "correlationidvalue";

  exports.defaultHeaders = {
    'X-Correlation-Id': `${correlationId}`,
    'Authorization': `Bearer ${token}`
  };
}}

###
GET /anything?a=b
...defaultHeaders

?? status == 200

POST /anything
{
  "x": "y"
}
...defaultHeaders

?? status == 200