/*
To add support for CHAI.JS with CHAI-STRING, make sure to:

- Use Node.JS v23.x (or higher).
- Add the most recent v4.x (not v5!) version of CHAI.JS to the project (e.g. npm install chai@4.5.0).

This should add the required dependencies to the project (package*.json files and node_modules folder).
*/

@host=https://httpbin.org
@value=abc

### Demo chai.js EXPECT (chai-string)
GET /anything?value={{value}}
{{
  const { expect } = require('chai');
  const chai = require('chai');
  chai.use(require('chai-string'));

  test(`args.value starts with ${value} via EXPECT`, () => {
    expect(response.parsedBody.args.value).to.startWith(value);
    expect(response.parsedBody.args.value).to.startWithIgnoreCase(value);
  });
}}

### Demo chai.js ASSERT (chai-string)
GET /anything?value={{value}}
{{
  const { assert } = require('chai');
  const chai = require('chai');
  chai.use(require('chai-string'));

  test(`args.value starts with ${value} via ASSERT`, () => {
    assert.startsWith(response.parsedBody.args.value, value);
    assert.startsWithIgnoreCase(response.parsedBody.args.value, value);
  });
}}

### Demo chai.js SHOULD (chai-string)
GET /anything?value={{value}}
{{
  require('chai').should();
  const chai = require('chai');
  chai.use(require('chai-string'));

  test(`args.value starts with ${value} via SHOULD`, () => {
    response.parsedBody.args.value.should.startWith(value);
    response.parsedBody.args.value.should.startWithIgnoreCase(value);
  });
}}
