@host=https://httpbin.org

{{+
  const token = "test";

  exports.defaultHeaders = {
    'Content-Type': 'text/html',
    'Authorization': `Bearer ${token}`
  };
}}

###
GET /anything?a=b
...defaultHeaders

?? status == 200

POST /anything
{
  "x": "y"
}
...defaultHeaders

?? status == 200