// The secret must obviously not be hard coded (normally should come from environment file)
@clientCreds_tokenEndpoint=https://some.auth.service.provider.com/token
@clientCreds_clientId=some_client_id
@clientCreds_clientSecret=some_client_secret
@clientCreds_useAuthorizationHeader=false
@clientCreds_scope=scopeA scopeB scopeC

### Authorization using OAuth 2.0 with client credentials (disabled)
/*
This test is disabled because there is no public demo endpoint to generate an OAuth token.
*/
# @disabled
GET https://some.endpoint.provider.com/api/v1/secured_service
Authorization: oauth2 client_credentials clientCreds

# See more examples at https://httpyac.github.io/guide/variables.html#oauth2-openid-connect
