### Test A
# @name testA
GET https://httpbin.org/json

### Test B
# @name testB
# @ref testA
{{
  // This condition should only cancel test B, but when run from CLI, all subsequent tests will be skipped.
  exports.$cancel = testAResponse.statusCode == 200;

  // If you change the condition from == to !=, all tests will run.
}}
GET https://httpbin.org/json

### Test C
# @name testC
POST https://httpbin.org/anything
{
  "a":"b"
}

### Test D
# @name testD
POST https://httpbin.org/anything
{
  "c":"d"
}